CREATE TABLE IF NOT EXISTS clientes (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
nombre VARCHAR (50),
apellido VARCHAR(50),
direccion VARCHAR(100),
telefono VARCHAR(100),
email VARCHAR(100) UNIQUE,
password VARCHAR(100),
fechaRegistro DATETIME DEFAULT CURRENT_TIMESTAMP
);
